export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const GET_ALL_DOCTORS_FAIL = "GET_ALL_DOCTORS_FAIL";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const MAKE_APPOINTMENT = "MAKE_APPOINTMENT";
export const GET_APPOINTMENTS_FAIL = "GET_APPOINTMENTS_FAIL";
export const MAKE_APPOINTMENT_FAIL = "MAKE_APPOINTMENT_FAIL";
export const CLEAR_APPOINTMENTS = "CLEAR_APPOINTMENTS";

export const GET_HELPER_APPOINTMENTS = "GET_HELPER_APPOINTMENTS";
export const GET_HELPER_APPOINTMENTS_FAIL = "GET_HELPER_APPOINTMENTS_FAIL";

export const GET_DOCTOR_WISE_VISITS = "GET_DOCTOR_WISE_VISITS";

export const GET_HELPER_ANC_VISITS = "GET_HELPER_ANC_VISITS";
export const GET_HELPER_ANC_VISITS_FAIL = "GET_HELPER_ANC_VISITS_FAIL";
